spring:
  profiles:
    include: oauth
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

jackson:
  serialization:
    fail-on-empty-beans: false

cloud:
  aws:
    credentials:
      accessKey: AKIA2A2FFZJ6LMWTOOXJ
      secretKey: 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
    s3:
      bucket: bobsimg
    region:
      static: ap-northeast-2
    stack:
      auto: false

#logging:
#  level:
#    root: debug1